FROM node:20-alpine AS builder

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
RUN yarn global add serve
EXPOSE 8080
CMD ["serve", "-s", "dist", "-l", "8080"]
