version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://server:3000
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/app/db.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
